# ini namanya Heading

mengecek apakah program dapat berjalan

In [2]:
1+1

2

Mengecek versi dari python

In [13]:
#mengetahui apakah versi python yang digunakan adalah python 2 atau 3
import platform
print(platform.python_version()) 

3.6.4


Variable

In [14]:
#memasukkan variabel
x=10
y=3
#melakukan operasi pada variabel
print(x)
print(y)
print(x+y)

10
3
13


Arithmetic

In [11]:
print(x+y)
print(x-y)
print(-x)
print(x*y)
print(x**y)
print(x/y)
print(x//y)
print(x%y)

13
7
-10
30
1000
3.3333333333333335
3
1


Boolean and Boolean Expression

In [20]:
#mencetak hasil benar atau salah
print(True)
print(False)

#mengetahui tipe data untuk true dan false
print(type(True))
print(type(False))

print(type('True'))
print(type('False'))

True
False
<class 'bool'>
<class 'bool'>
<class 'str'>
<class 'str'>


ketika menggunakan "" maka tipe data akan berubah menjadi string, sedangkan tanpa "" data akan memiliki tipe boolean

In [28]:
#melakukan operasi terhadap data boolean
t=True
f=False
print(type(t))
print(t and f)
print(t or f)
print(not t)
print(t!=f)

<class 'bool'>
False
True
False
True


List

In [47]:
#list biasa
fam=[2,3,4,5,6,7]
print(fam)
print(type(fam))

#list dalam list
Data=[['Bob',160],['Charlie',150],['Brian',140.5]]
#mencetak variabel dan typenya
print(Data)
print(type(Data))
#mencetak inkdeks pertama dari variabel dan typenya
print(Data[0])
print(type(Data[0]))
#mencetak nilai pertama dari indeks pertama variabel dan typenya
print(Data[0][0])
print(type(Data[0][0]))
#mencetak nilai kedua dari indeks pertama variabel dan typenya
print(Data[0][1])
print(type(Data[0][1]))

[2, 3, 4, 5, 6, 7]
<class 'list'>
[['Bob', 160], ['Charlie', 150], ['Brian', 140.5]]
<class 'list'>
['Bob', 160]
<class 'list'>
Bob
<class 'str'>
160
<class 'int'>


In [68]:
nums=list(range(5))
#mencetak isi list keseluruhan
print(nums)
print(" ")

#SCLICING
#mencetak list pada indeks ke 2 sampe 4 
print('indeks ke 2 sampe 4 adalah ',nums[2:4])
#mencetak list mulai dari indeks ke2 sampai selesai
print('indeks ke2 sampai selesai adalah ',nums[2:])
#mencetak list mulai dari awal sampai indeks ke 1
print('list mulai dari awal sampai indeks ke 1 adalah ',nums[:2])
#mencetak list dari awal sampai akhir
print('list dari awal sampai akhir adalah ',nums[:])
#mencetak list dari awal sampai angka kedua dari akhir
print('list dari awal sampai angka kedua dari akhir',nums[:-1])
print(' ')

#REPLACE
#mengubah nilai list pada indeks ke 2 dan 3
nums[2:4]=[8,9]
#mencetak listy baru yang sudah diubah
print('list yang baru adalah ',nums)
print('list adalah{}'.format(nums)) 
print('list adalah:{:0.2f}'.format(nums[1])) #untuk foromat 2 angka di belakang koma

[0, 1, 2, 3, 4]
 
indeks ke 2 sampe 4 adalah  [2, 3]
indeks ke2 sampai selesai adalah  [2, 3, 4]
list mulai dari awal sampai indeks ke 1 adalah  [0, 1]
list dari awal sampai akhir adalah  [0, 1, 2, 3, 4]
list dari awal sampai angka kedua dari akhir [0, 1, 2, 3]
 
list yang baru adalah  [0, 1, 8, 9, 4]
list adalah[0, 1, 8, 9, 4]
list adalah:1.00


In [75]:
#DELETE
#pop
Data=[['Bob',160],['Charlie',150],['Brian',140.5]] #data awal
print(Data) #cetak data
print(Data.pop()) #data apa yang bakal kebuang saat di pop
print(Data) #data yang sudah dibuang 1 
print(Data.pop(0))#data yang akan dibuang pada indeks 0
print(Data) #data yang sudah di pop pertama dan kedua

[['Bob', 160], ['Charlie', 150], ['Brian', 140.5]]
['Brian', 140.5]
[['Bob', 160], ['Charlie', 150]]
['Bob', 160]
[['Charlie', 150]]


In [84]:
#MENYISIPKAN
N=list(range(10))
print(N)
N.insert(3,12)
print(N)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[0, 1, 2, 12, 3, 4, 5, 6, 7, 8, 9]


Function

In [96]:
N=list(range(10))
print(N)
print(max(N))
print(min(N))
print(len(N))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
9
0
10


Fungsi if

In [95]:
def label_height(height):
    """This is to lable height"""
    if height>150:#pake and kalo misal ada 2 syarat
        label="tinggi"
    elif height<=150:
        label="kurang tinggi"
    else:
        label="lain-lain"
    return label
label_height(170)

'tinggi'

In [105]:
Data=[['Bob',160],['Charlie',150],['Brian',140.5]]

#misahin nama sama tinggi badan
name_list=[row[0] for row in Data]
height_list=[row[1] for row in Data]
#cetak list baru yang udah dipisah
print(name_list)
print(height_list)

#jalanin fungsi pada keseluruhan list
print(list(map(label_height,fam)))
print(list(map(label_height,height_list)))

['Bob', 'Charlie', 'Brian']
[160, 150, 140.5]
['kurang tinggi', 'kurang tinggi', 'kurang tinggi', 'kurang tinggi', 'kurang tinggi', 'kurang tinggi']
['tinggi', 'kurang tinggi', 'kurang tinggi']


In [113]:
nums=list(range(10))
print(nums)
squares=[x ** 2 for x in nums]
print(squares)
cubic=list(map(lambda x:x**3,nums))
print(cubic)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]
[0, 1, 8, 27, 64, 125, 216, 343, 512, 729]


Method

In [116]:
import numpy as np
#mengubah height_list menjadi bentuk array
height_array =np.array(height_list)
print(height_array)
print(type(height_array))

#bisa melakukan perhitungan untuk list
height_array=height_array-10
print(height_array)

[160.  150.  140.5]
<class 'numpy.ndarray'>
[150.  140.  130.5]


In [135]:
x=np.array([[1,2,3],[4,5,6]])
print(type(x))
print(x.dtype)
print(x.shape)

print(" ")
print("perhitungan set data")

#perhitungan set data
print(x)
print(x.flatten())
print(x.transpose())
print(x.reshape([2,3]))

print(" ")
print("Mengoperasikan atas bawah(kolom)")

#Mengoperasikan atas bawah
print(x.sum(axis=0))
print(x.mean(axis=0))
print(x.std(axis=0))
print(x.min(axis=0))
print(x.max(axis=0))

print(" ")
print("Menjumlahkan kanan kiri(baris)")

#Menjumlahkan kanan kiri
print(x.sum(axis=1))
print(x.mean(axis=1))
print(x.std(axis=1))
print(x.min(axis=1))
print(x.max(axis=1))

<class 'numpy.ndarray'>
int32
(2, 3)
 
perhitungan set data
[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]
[[1 4]
 [2 5]
 [3 6]]
[[1 2 3]
 [4 5 6]]
 
Mengoperasikan atas bawah(kolom)
[5 7 9]
[2.5 3.5 4.5]
[1.5 1.5 1.5]
[1 2 3]
[4 5 6]
 
Menjumlahkan kanan kiri(baris)
[ 6 15]
[2. 5.]
[0.81649658 0.81649658]
[1 4]
[3 6]


dtype digunakan untuk mengetahui tipe data
shape digunakan untuk mengetahui bari dan kolom dari list

In [146]:
countries = ['spain', 'france', 'germany','norway']
capitals = ['madrid', 'paris', 'berlin', 'oslo']
ind_ger = countries.index('germany')
print(capitals[ind_ger])
europe = {'spain':'madrid', 'france':'paris', 'germany':'berlin', 'norway':'oslo'}
type(europe)
print(europe)
print(europe.keys())
print(europe.values())

berlin
{'spain': 'madrid', 'france': 'paris', 'germany': 'berlin', 'norway': 'oslo'}
dict_keys(['spain', 'france', 'germany', 'norway'])
dict_values(['madrid', 'paris', 'berlin', 'oslo'])


In [147]:
code=['US','AUS','JPN','IN','RUS','MOR','EG']
names=['United State','Australia','India','Japan','Russia','Morocco','Egypt']
dr=[True,False,False,False,True,True,True]
cpc=[809,731,588,18,200,70,45]
my_dict={'ctrcode':code,'country':names,'drives_right':dr,'cars_per_cap':cpc}
my_dict.values()

dict_values([['US', 'AUS', 'JPN', 'IN', 'RUS', 'MOR', 'EG'], ['United State', 'Australia', 'India', 'Japan', 'Russia', 'Morocco', 'Egypt'], [True, False, False, False, True, True, True], [809, 731, 588, 18, 200, 70, 45]])

In [154]:
import pandas as pd
cars=pd.DataFrame(my_dict)
print(type(cars))
print(cars)
#meyebutkan namanama kolom pada variabel cars
print(cars.columns)

#mengetahui jumlah data
print(len(cars.columns)) #mengatahui jumlah kolom pada variabel cars
print(len(cars))#mengetahui jumlah data variabel cars

print(" ")
#menampilkan 3 data teratas dan 3 data terbawah
print(cars.head(3))
print(" ")
print(cars.tail(3))

<class 'pandas.core.frame.DataFrame'>
   cars_per_cap       country ctrcode  drives_right
0           809  United State      US          True
1           731     Australia     AUS         False
2           588         India     JPN         False
3            18         Japan      IN         False
4           200        Russia     RUS          True
5            70       Morocco     MOR          True
6            45         Egypt      EG          True
Index(['cars_per_cap', 'country', 'ctrcode', 'drives_right'], dtype='object')
4
7
 
   cars_per_cap       country ctrcode  drives_right
0           809  United State      US          True
1           731     Australia     AUS         False
2           588         India     JPN         False
 
   cars_per_cap  country ctrcode  drives_right
4           200   Russia     RUS          True
5            70  Morocco     MOR          True
6            45    Egypt      EG          True


In [166]:
print(cars.dtypes)
print(" ")
print(cars.info)

cars_per_cap     int64
country         object
ctrcode         object
drives_right      bool
dtype: object
 
<bound method DataFrame.info of    cars_per_cap       country ctrcode  drives_right
0           809  United State      US          True
1           731     Australia     AUS         False
2           588         India     JPN         False
3            18         Japan      IN         False
4           200        Russia     RUS          True
5            70       Morocco     MOR          True
6            45         Egypt      EG          True>


In [167]:
cars.describe()

cars_per_cap
count      7.000000
mean     351.571429
std      345.595552
min       18.000000
25%       57.500000
50%      200.000000
75%      659.500000
max      809.000000

In [170]:
mobil=cars.set_index("ctrcode")
mobil

cars_per_cap       country  drives_right
ctrcode                                          
US                809  United State          True
AUS               731     Australia         False
JPN               588         India         False
IN                 18         Japan         False
RUS               200        Russia          True
MOR                70       Morocco          True
EG                 45         Egypt          True

In [173]:
print(cars[['country','drives_right']])

        country  drives_right
0  United State          True
1     Australia         False
2         India         False
3         Japan         False
4        Russia          True
5       Morocco          True
6         Egypt          True


Kalo mau ambil satu atau lebih kolom dari sebuah data frame jangan lupa kurung kotaknya dua supaya pas ke ambil tetep bentuknya data frame bukan jadi series. kalo jadi series nanti bisa error kalo diambil dua


In [177]:
print(mobil[0:3])

         cars_per_cap       country  drives_right
ctrcode                                          
US                809  United State          True
AUS               731     Australia         False
JPN               588         India         False


Loc iloc

In [181]:
#print observasi dari australie dan egypt
print(mobil)
print(mobil.loc[['AUS','EG']])
print(mobil.iloc[[1,6]])

         cars_per_cap       country  drives_right
ctrcode                                          
US                809  United State          True
AUS               731     Australia         False
JPN               588         India         False
IN                 18         Japan         False
RUS               200        Russia          True
MOR                70       Morocco          True
EG                 45         Egypt          True
         cars_per_cap    country  drives_right
ctrcode                                       
AUS               731  Australia         False
EG                 45      Egypt          True
         cars_per_cap    country  drives_right
ctrcode                                       
AUS               731  Australia         False
EG                 45      Egypt          True


syaratnya nama yang dicari harus dijadiin index terlebih dahulu. untuk locnya pake namanya langsung, kalo iloc digunain langsung pake indexnya

In [183]:
print(mobil.loc[['RUS','MOR'],['country','drives_right']])
print(mobil.iloc[[4,5],[1,2]])

         country  drives_right
ctrcode                       
RUS       Russia          True
MOR      Morocco          True
         country  drives_right
ctrcode                       
RUS       Russia          True
MOR      Morocco          True


Tulis baris dulu baru kolom

In [211]:
print(mobil[mobil.drives_right==True])
#filter dengan menggunakan 2 syarat (AND)
print(mobil[(mobil.cars_per_cap>100) & (mobil.drives_right==False)])
#filter dengan menggunakan 2 syarat(OR)
print(mobil[(mobil.cars_per_cap>100) | (mobil.drives_right==False)])      

         cars_per_cap       country  drives_right
ctrcode                                          
US                809  United State          True
RUS               200        Russia          True
MOR                70       Morocco          True
EG                 45         Egypt          True
         cars_per_cap    country  drives_right
ctrcode                                       
AUS               731  Australia         False
JPN               588      India         False
         cars_per_cap       country  drives_right
ctrcode                                          
US                809  United State          True
AUS               731     Australia         False
JPN               588         India         False
IN                 18         Japan         False
RUS               200        Russia          True


Dipake untuk ngambil dengan satu syarat yaitu drives rightnya true

In [212]:
#mengurutkan data berdasarkan kolom cars_per_cap
print(mobil.sort_values(by=['cars_per_cap']))
print(mobil.sort_values(by=['cars_per_cap'],ascending=False))

         cars_per_cap       country  drives_right
ctrcode                                          
IN                 18         Japan         False
EG                 45         Egypt          True
MOR                70       Morocco          True
RUS               200        Russia          True
JPN               588         India         False
AUS               731     Australia         False
US                809  United State          True
         cars_per_cap       country  drives_right
ctrcode                                          
US                809  United State          True
AUS               731     Australia         False
JPN               588         India         False
RUS               200        Russia          True
MOR                70       Morocco          True
EG                 45         Egypt          True
IN                 18         Japan         False
