In [1]:
import pandas as pd
import numpy as np
from sklearn import preprocessing
from collections import OrderedDict
from sklearn.metrics import confusion_matrix, classification_report
import matplotlib.pyplot as plt 
from sklearn.linear_model import LogisticRegression
from sklearn.cross_validation import train_test_split
import seaborn as sns
from sklearn.utils import shuffle

C:\Users\nikita059240\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


In [2]:
nama = ["Brian", "Joe","Sarah","Julia"]
gender = ["Male", "Male","Female","Female"]
marital = ["Married", "Single", "Married", "Single"]

In [3]:
my_dict = {'nama':nama, 'gender':gender, 'marital':marital}

In [4]:
#without OrderedDict
employee = pd.DataFrame(my_dict)
employee

gender  marital   nama
0    Male  Married  Brian
1    Male   Single    Joe
2  Female  Married  Sarah
3  Female   Single  Julia

In [14]:
#with OrderedDict
employee = pd.DataFrame(OrderedDict(my_dict))
employee

predicted  actual
0          1       1
1          1       0
2          0       1
3          0       1
4          0       0
5          1       1
6          1       1
7          1       1
8          0       0
9          0       0

# Encoding 1, with drop_first=false(default)

In [6]:
employee2=pd.get_dummies(employee,columns=["gender","marital"])
employee2

nama  gender_Female  gender_Male  marital_Married  marital_Single
0  Brian              0            1                1               0
1    Joe              0            1                0               1
2  Sarah              1            0                1               0
3  Julia              1            0                0               1

# Encoding 1, withour drop_first= TRUE

In [7]:
employee3=pd.get_dummies(employee,columns=["gender","marital"], drop_first=True)
employee3

nama  gender_Male  marital_Single
0  Brian            1               0
1    Joe            1               1
2  Sarah            0               0
3  Julia            0               1

# Case

In [8]:
predicted = [1,1,0,0,0,1,1,1,0,0]
actual = [1,0,1,1,0,1,1,1,0,0]

In [9]:
my_dict={'predicted':predicted,'actual':actual}

In [10]:
print(classification_report(actual, predicted))

             precision    recall  f1-score   support

          0       0.60      0.75      0.67         4
          1       0.80      0.67      0.73         6

avg / total       0.72      0.70      0.70        10



In [11]:
#Build confusion Matrix
cm = confusion_matrix(actual, predicted)
cm

array([[3, 1],
       [2, 4]], dtype=int64)

In [12]:
total = sum(sum(cm))
accuracy = (cm[0,0] + cm[1,1]) / total
sensitivity = cm[1,1]/(cm[1,0]+cm[1,1])
specificity = cm[0,0]/(cm[0,0]+cm[0,1])

In [13]:
print('Confusion Matrix : \n', cm)
print('Accuracy : ', accuracy)
print('Sensitivity : ', sensitivity)
print('Specificity : ', specificity)

Confusion Matrix : 
 [[3 1]
 [2 4]]
Accuracy :  0.7
Sensitivity :  0.6666666666666666
Specificity :  0.75


# Excercise

In [17]:
predicted2 = ['T','T','T','F','F','T','T','T','F','F']
actual2    = ['T','T','F','F','F','T','T','F','F','F']

1. Build Confusion Matrix
2. Calculate Accuracy, Sensitivity, Specificity, Precision

In [18]:
cm1 = confusion_matrix(actual2, predicted2)
cm1

array([[4, 2],
       [0, 4]], dtype=int64)

In [19]:
total = sum(sum(cm1))
accuracy = (cm1[0,0] + cm1[1,1]) / total
sensitivity = cm1[1,1]/(cm1[1,0]+cm1[1,1])
specificity = cm1[0,0]/(cm1[0,0]+cm1[0,1])

In [21]:
print('Confusion Matrix : \n', cm1)
print('Accuracy : ', accuracy)
print('Sensitivity : ', sensitivity)
print('Specificity : ', specificity)

Confusion Matrix : 
 [[4 2]
 [0 4]]
Accuracy :  0.8
Sensitivity :  1.0
Specificity :  0.6666666666666666


In [22]:
my_dict2={'predicted':predicted2,'actual':actual2}

In [23]:
predict2 = pd.DataFrame(OrderedDict(my_dict2))
predict2

predicted actual
0         T      T
1         T      T
2         T      F
3         F      F
4         F      F
5         T      T
6         T      T
7         T      F
8         F      F
9         F      F